apiVersion: v1
kind: Endpoints
metadata:
        name: mongo
subsets:
        - addresses:
                - ip: 192.168.0.158
                - ip: 192.168.0.222
          ports:
                - port: 8635
